fix: add parser metadata for eslint 9 cache
When using `eslint-config-next` on eslint 9.x with a flat config (as per next.js [docs](https://nextjs.org/docs/app/api-reference/config/eslint#specifying-a-root-directory-within-a-monorepo)) and with the `--cache` flag - eslint would fail:

```
> ./node_modules/.bin/eslint --cache

Oops! Something went wrong! :(

ESLint: 9.17.0

TypeError: Cannot serialize key "parse" in parser: Function values are not supported.
    at languageOptionsToJSON (.../next-eslint-issue/node_modules/eslint/lib/config/config.js:113:23)
    at languageOptionsToJSON (.../next-eslint-issue/node_modules/eslint/lib/config/config.js:107:35)
    at Config.toJSON (.../next-eslint-issue/node_modules/eslint/lib/config/config.js:260:30)
    at stringify (.../next-eslint-issue/node_modules/json-stable-stringify-without-jsonify/index.js:25:25)
    at module.exports (.../next-eslint-issue/node_modules/json-stable-stringify-without-jsonify/index.js:68:7)
    at hashOfConfigFor (.../next-eslint-issue/node_modules/eslint/lib/cli-engine/lint-result-cache.js:50:75)
    at LintResultCache.getCachedLintResults (.../next-eslint-issue/node_modules/eslint/lib/cli-engine/lint-result-cache.js:116:30)
    at .../next-eslint-issue/node_modules/eslint/lib/eslint/eslint.js:783:41
    at async Promise.all (index 0)
    at async ESLint.lintFiles (.../next-eslint-issue/node_modules/eslint/lib/eslint/eslint.js:759:25)
```

(see a minimal repro here: https://github.com/CvX/next-eslint-issue)

This happens because eslint is unable to serialize the `parser` object in the config. Adding metadata fixes that.

The issue was originally reported over at eslint repo in: https://github.com/eslint/eslint/issues/19322