Add check for parsedUrl.query
Adding rewrites to next.config.js can cause parsedUrl.query to be undefined, which then breaks the application in production mode (not development mode).

This type of error could be experienced:
TypeError: Cannot read property '__nextLocale' of undefined
    at Router.execute (...\node_modules\next\dist\next-server\server\router.js:19:712)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.run (...\node_modules\next\dist\next-server\server\next-server.js:69:1042)

Adding a check for parsedUrl.query prevents the error, and the application functions as expected.