Add ts-node dependency for jest.config.ts parsing (#70971)
<!-- Thanks for opening a PR! Your contribution is much appreciated.
To make sure your PR is handled as smoothly as possible we request that
you follow the checklist sections below.
Choose the right checklist for the change(s) that you're making:

## For Contributors

### Improving Documentation

- Run `pnpm prettier-fix` to fix formatting issues before opening the
PR.
- Read the Docs Contribution Guide to ensure your contribution follows
the docs guidelines:
https://nextjs.org/docs/community/contribution-guide

### Adding or Updating Examples

- The "examples guidelines" are followed from our contributing doc
https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- Make sure the linting passes by running `pnpm build && pnpm lint`. See
https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

### Fixing a bug

- Related issues linked using `fixes #number`
- Tests added. See:
https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs
- Errors have a helpful link attached, see
https://github.com/vercel/next.js/blob/canary/contributing.md

### Adding a feature

- Implements an existing feature request or RFC. Make sure the feature
request has been accepted for implementation before opening a PR. (A
discussion must be opened, see
https://github.com/vercel/next.js/discussions/new?category=ideas)
- Related issues/discussions are linked using `fixes #number`
- e2e tests added
(https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs)
- Documentation added
- Telemetry added. In case of a feature if it's used or not.
- Errors have a helpful link attached, see
https://github.com/vercel/next.js/blob/canary/contributing.md


## For Maintainers

- Minimal description (aim for explaining to someone not on the team to
understand the PR)
- When linking to a Slack thread, you might want to share details of the
conclusion
- Link both the Linear (Fixes NEXT-xxx) and the GitHub issues
- Add review comments if necessary to explain to the reviewer the logic
behind a change

### What?

### Why?

### How?

Closes NEXT-
Fixes #

-->

### What?

Fix the error with Jest trying to set up Jest using the `jest.config.ts`
file suggested by the docs

```bash
$ pnpm jest
Error: Jest: Failed to parse the TypeScript config file /Users/k/p/next-js-example-fall-2024-atvie/jest.config.ts
  Error: Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
```

Unfortunately the `pnpm create jest@latest` command does not add this
required dependency, [because of `esbuild-register` support in Jest v30
alpha](https://github.com/jestjs/jest/issues/14752#issuecomment-2268371568)

### Why?

Because [the Jest docs
page](https://nextjs.org/docs/canary/app/building-your-application/testing/jest)
suggests `jest.config.ts` by default

### How?

Use `ts-node` to load `jest.config.ts`

### Alternatives Considered

Use `esbuild-register` with custom config comment in Jest v30 alpha:

- https://github.com/jestjs/jest/pull/15190

Co-authored-by: JJ Kasper <jj@jjsweb.site>