fix(examples): fix tests in examples/with-mocha/
The tests were failing:

```console
$ pnpm test  # Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
$ pnpm i -D @babel/runtime
$ pnpm test  # Error: Package subpath './lib/utils' is not defined by "exports" in /src/with-mocha/node_modules/.pnpm/enzyme@3.11.0/node_modules/cheerio/package.json
```

Since Enzyme doesn't support React 18, migrate to React Testing Library.