Revert "[image, link] fix ref merging for callback refs that return a cleanup function" (#68176)
Seems this is causing us to hit the following error our vercel-site

```sh
 ReferenceError: navigator is not defined
vercel-site:build:     at s (/vercel/path0/apps/vercel-site/.next/server/chunks-EDOwHfQ0FCxDTUqmP-83_/65787.js:161:168406)
vercel-site:build:     at u (/vercel/path0/apps/vercel-site/.next/server/chunks-EDOwHfQ0FCxDTUqmP-83_/65787.js:50:154810)
```

Reverts vercel/next.js#68123