fix(examples): fix test in examples/with-cypress/
Fix the following error by bumping cypress to the latest.

```console
$ pnpm component:headless

> @ component:headless /src/with-cypress
> cypress run --component

Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

TypeError: webpackModule.init is not a function
    at sourceNextWebpack (/home/wsh/.cache/Cypress/12.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:252:19)
    at sourceNextWebpackDeps (/home/wsh/.cache/Cypress/12.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:212:21)
    at nextHandler (/home/wsh/.cache/Cypress/12.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:18:74)
    at async getPreset (/home/wsh/.cache/Cypress/12.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:74:20)
    at async devServer.create (/home/wsh/.cache/Cypress/12.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:93:61)
    at async /home/wsh/.cache/Cypress/12.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:25:24
 ELIFECYCLE  Command failed with exit code 1.
```