(E2E) Log which config file is used for `next start` (#73105)
# Context

[Test
run](https://github.com/vercel/next.js/actions/runs/11962411287/job/33382985253?pr=73030#step:29:421)
fails due to

```
   ▲ Next.js 15.0.4-canary.22
   - Local:        http://[::1]:35903
   - Network:      http://[::]:35903

 ✓ Starting...
Error: "next start" does not work with "output: export" configuration. Use "npx serve@latest out" instead.
    at <unknown> (dist/server/next.js:215:31)
    at async NextServer.prepare (dist/server/next.js:154:24)
    at async initializeImpl (dist/server/lib/render-server.js:92:5)
    at async initialize (dist/server/lib/router-server.js:436:22)
    at async Server.<anonymous> (dist/server/lib/start-server.js:272:36)
```

However, there was no `output: export` specified in the [test
setup](https://github.com/vercel/next.js/tree/jude/which-config-are-we-using/test/integration/edge-runtime-configurable-guards).
**Mysterious!**

# Hypothesis

`next start` recursively finds the `next.config` upwards in the
directory tree and happens to locate an extraneous `next.config` that
specified `output: export`.

# Changes

- Output the config file path in test mode for future debugging
- Short-circuit `findUp` for the broken test by placing an empty config
in the project directory