fix: 💯 typescript issue with-jest example
So there are some toBe property's with React-testing-library that when written shows this error:
Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.
the commit fixes it✅