fix: Disallow empty hostname in remote pattern validation
> Build error occurred
TypeError: Expected a non-empty string
    at Array.map (*<anonymous>*)
error Command failed with exit code 1.

When my build failed with the above error; I couldn’t figure out until a very long time where was the Source of the error. Hence, it would be good to know the origin of the error more precisely.