Do not mutate context with `.sort()`
React 19 does not want you to mutate properties or context values. We create copies with `[...myArray]`.

In prod environments, this caused a vague error

```
TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
```