Revert react-server-dom require change (#55345)
Reverts a piece of https://github.com/vercel/next.js/pull/55287 which seems to break edge-functions. We'll need to investigate an alternative and add a test case to ensure it fixes the case as expected. 

```sh
Error: The Edge Function "hello/world/dashboard/another-edge" is referencing unsupported modules:
--
- index.js: react-server-dom-webpack/client.edge
```

x-ref: https://github.com/vercel/vercel/actions/runs/6177961848/job/16770369085?pr=10504#step:9:308