Bump vendored sass-loader version (#70067)
Bump sass-loader to include
https://github.com/webpack-contrib/sass-loader/pull/1141.

Closes PACK-2447

Previously sass-loader called `this.async()()` when failing to load the
dependency, which meant that
the following Webpack loaders still run (because that call is passes
`error = undefined` and `content = undefined`).
That PR changes it to `this.async()(err)`.

This in turn changes the **Turbopack** error message in this case from
```
resolve-url-loader: PostCSS error
PostCSS received undefined instead of string
```
to
```
Error evaluating Node.js code
Error: Cannot find module 'sass'
```

I upgraded to sass-loader 15 because 16 has a pretty breaking change
regarding options:
https://github.com/webpack-contrib/sass-loader/releases/tag/v16.0.0

[Breaking sass-loader changes between 12.6.0 and
15.0.0](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md):

- 15.0.0 (2024-07-23)
    - prefer sass-embedded over sass by default
- 14.0.0 (2024-01-15)
    - removed `fibers` support
    - minimum supported Node.js version is 18.12.0
- 13.0.0
    - minimum supported Node.js version is 14.15.0
- emit `@warn` at-rules as webpack warnings by default, if you want to
revert behavior please use the warnRuleAsWarning option