Allow running `ncc` before `pnpm build` (#97234)
Fixes 
```
[17:03:12] ncc_mswjs_interceptors failed because [tsl] ERROR in /home/runner/work/next.js/next.js/packages/next/src/server/og/cache-image-response.ts(27,17)
      TS2307: Cannot find module 'next/dist/compiled/@vercel/og/index.node.js' or its corresponding type declarations.
```
--
https://github.com/vercel/next.js/actions/runs/31515393262/job/93859146712#step:8:723

Now we use externalize the `Promise.withResolvers` polyfill to allow
running `ncc` before we built `dist`.