[test] Remove rogue debug log (#88423)
Logging the work unit store caused the following runtime error under
some circumstances:

```
TypeError: Cannot read private member #headersList from an object whose class did not declare it
```