fix: allow empty string value for opengraph (#68262)
### Why?

When passing an empty string value `''` to `metadata.openGraph.authors`,
it gives an error:

```
Error: n.map is not a function
```

It is because we set the value to the `ResolvedOpenGraph` if it is
truthy.

```ts
if (value) {
 // ...
}
```

### How?

Assign the resolved value from `resolveArray` and only if not nullish.


https://github.com/vercel/next.js/blob/571597d8ee464113e24494591ed693f82b710d16/packages/next/src/lib/metadata/generate/utils.ts#L1-L6

Fixes https://github.com/vercel/next.js/issues/68259
Fixes NDX-125

---------

Co-authored-by: Jiachi Liu <inbox@huozhi.im>