Turbopack: pass RcStr to AnalyzeIssue (#99166)
These were only ever `StyledString::Text` anyway. So just store the
RcStr directly

Simplify the code to fix these lint errors
```
➜  next.js-other git:(canary) ✗ pnpm sg scan
error[no-map-async-cell]: Using `.map(async |...| { ...cell() })` causes non-deterministic cell order
    ┌─ turbopack/crates/turbopack-core/src/module_graph/mod.rs:766:33
    │    
722 │ ╭               modules
723 │ │                   .iter()
724 │ │                   .map(async |m| {
    │ │ ╭──────────────────────'
    · │ │
766 │ │ │                                 Vc::cell(rcstr!("Module graph is missing an entry point")),
    │ │ │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    · │ │
798 │ │ │                 })
    │ ╰─│──────────────────'
    │   ╰─────────────────'
    │    
    = You probably want to first try_join() the async computations before wrapping them in a cell.

error[no-map-async-cell]: Using `.map(async |...| { ...cell() })` causes non-deterministic cell order
    ┌─ turbopack/crates/turbopack-core/src/module_graph/mod.rs:767:33
    │      
722 │   ╭               modules
723 │   │                   .iter()
724 │   │                   .map(async |m| {
    │   │ ╭──────────────────────'
    ·   │ │
767 │ ╭ │ │                                 StyledString::Text(rcstr!(
    · │ │ │
771 │ │ │ │                                 .cell(),
    │ ╰─│─│───────────────────────────────────────^
    ·   │ │
798 │   │ │                 })
    │   ╰─│──────────────────'
    │     ╰─────────────────'
    │      
    = You probably want to first try_join() the async computations before wrapping them in a cell.

Error: 2 error(s) found in code.
Help: Scan succeeded and found error level diagnostics in the codebase.

➜  next.js-other git:(canary) ✗ 
```