Upgrade rustc to nightly-2026-10-04 (#99682)
- ~~Blocked by https://github.com/swc-project/plugins/pull/662 because
box_patterns was removed~~
- ~~Blocked on
https://github.com/rust-lang/miri/commit/87c4b123697e210ba99c5fc004049bb59acb2df0
so that Miri just works again~~
- Upgrade napi-build for https://github.com/napi-rs/napi-rs/pull/3492 to
fix `duplicate symbol: _initialize` in WASM

Still running into
```
@next/swc:test-cargo-unit-miri:     error: unsupported operation: fdatasync is only supported on file-backed file descriptors
@next/swc:test-cargo-unit-miri:         --> /home/runner/.rustup/toolchains/nightly-2026-10-06-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/fs/unix.rs:1279:13
@next/swc:test-cargo-unit-miri:          |
@next/swc:test-cargo-unit-miri:     1279 |             libc::fdatasync(fd)
@next/swc:test-cargo-unit-miri:          |             ^^^^^^^^^^^^^^^^^^^ unsupported operation occurred here
@next/swc:test-cargo-unit-miri:          |
@next/swc:test-cargo-unit-miri:          = help: this is likely not a bug in the program; it indicates that the program performed an operation that Miri does not support
@next/swc:test-cargo-unit-miri:          = note: this is on thread `tests::whole_ke`
@next/swc:test-cargo-unit-miri:          = note: stack backtrace:
@next/swc:test-cargo-unit-miri:                  0: std::sys::fs::unix::File::datasync::os_datasync
@next/swc:test-cargo-unit-miri:                      at /home/runner/.rustup/toolchains/nightly-2026-10-06-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/fs/unix.rs:1279:13: 1279:32
@next/swc:test-cargo-unit-miri:                  1: std::sys::fs::unix::File::datasync::{closure#0}
@next/swc:test-cargo-unit-miri:                      at /home/runner/.rustup/toolchains/nightly-2026-10-06-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/fs/unix.rs:1258:27: 1258:56
@next/swc:test-cargo-unit-miri:                  2: std::sys::pal::unix::cvt_r::<i32, {closure@std::sys::fs::unix::File::datasync::{closure#0}}>
@next/swc:test-cargo-unit-miri:                      at /home/runner/.rustup/toolchains/nightly-2026-10-06-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/mod.rs:250:19: 250:22
@next/swc:test-cargo-unit-miri:                  3: std::sys::fs::unix::File::datasync
@next/swc:test-cargo-unit-miri:                      at /home/runner/.rustup/toolchains/nightly-2026-10-06-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/fs/unix.rs:1258:9: 1258:59
@next/swc:test-cargo-unit-miri:                  4: std::fs::File::sync_data
@next/swc:test-cargo-unit-miri:                      at /home/runner/.rustup/toolchains/nightly-2026-10-06-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/fs.rs:823:9: 823:30
@next/swc:test-cargo-unit-miri:                  5: fs_err::File::sync_data
@next/swc:test-cargo-unit-miri:                      at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fs-err-3.3.1/src/file.rs:109:9: 110:25
@next/swc:test-cargo-unit-miri:                  6: db::commit_current::{closure#0}
@next/swc:test-cargo-unit-miri:                      at turbopack/crates/turbo-persistence/src/db.rs:252:25: 252:40
```