Turbopack: fix `Unknown module type` error for imports in webpack loaders (#99088)
Fixes an error like
```
./node_modules/.pnpm/@esbuild+linux-x64@0.28.1/node_modules/@esbuild/linux-x64/README.md
Error: Unknown module type
This module doesn't have an associated type. Use a known file extension, or register a loader for it.
```

Regression from https://github.com/vercel/next.js/pull/95732