Turbopack: rscModuleMapping without extra chunks (#71326)
- Also refactors `AppEndpoint` a bit (pulling code out into functions
and hoist common function calls for Node/Edge)
- Use the `server/app/.../page.js` RSC entry chunks in the
`rscModuleMapping` to not have to generate extra chunks.

Alternative implementation for
https://github.com/vercel/next.js/pull/71304
Closes #71304

- [x] ~~It fails with this strange error though:~~
```
Error: Cannot find module '../chunks/ssr/[turbopack]_runtime.js'
Require stack:
next.js/test/e2e/app-dir/use-cache/.next/server/chunks/ssr/[turbopack]_runtime.js
next.js/test/e2e/app-dir/use-cache/.next/server/app/page.js
```

---------

Co-authored-by: Hendrik Liebau <mail@hendrik-liebau.de>