Handle duplex automatically for NextRequest (#76531)
When configuring a body with `NextRequest` in node runtime without the
`duplex: 'half'` option it can throw an error un-necessarily since it's
an extension of the node `Request` instance. This auto-configures
`duplex: 'half'` when using `NextRequest` for easier migration from edge
-> node runtime for middleware.

```sh
TypeError: RequestInit: duplex option is required when sending a body.
    at new Request (/opt/rust/undici-runtime.js:40:31096)
```

x-ref: [slack
thread](https://vercel.slack.com/archives/C07LQPFERGF/p1740490607381379)