A little bit of maintenance on the ReasonML examples (#11662)
* Add babel-types package

`next dev` was failing with:

```
Error: Cannot find module 'babel-types'
```

* Upgrade to the latest bs-platform

Also add the `babel-types` package to stop the `next dev` command from complaining.

* Remove extraneous babel-plugin-bucklescript dependency.

Seems the dependency has been deprecated, and it doesn't seem to be required
anyways.