chore: update rspack to 1.3.9 (#78984)
<!-- Thanks for opening a PR! Your contribution is much appreciated.
To make sure your PR is handled as smoothly as possible we request that
you follow the checklist sections below.
Choose the right checklist for the change(s) that you're making:

## For Contributors

### Improving Documentation

- Run `pnpm prettier-fix` to fix formatting issues before opening the
PR.
- Read the Docs Contribution Guide to ensure your contribution follows
the docs guidelines:
https://nextjs.org/docs/community/contribution-guide

### Adding or Updating Examples

- The "examples guidelines" are followed from our contributing doc
https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- Make sure the linting passes by running `pnpm build && pnpm lint`. See
https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

### Fixing a bug

- Related issues linked using `fixes #number`
- Tests added. See:
https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs
- Errors have a helpful link attached, see
https://github.com/vercel/next.js/blob/canary/contributing.md

### Adding a feature

- Implements an existing feature request or RFC. Make sure the feature
request has been accepted for implementation before opening a PR. (A
discussion must be opened, see
https://github.com/vercel/next.js/discussions/new?category=ideas)
- Related issues/discussions are linked using `fixes #number`
- e2e tests added
(https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs)
- Documentation added
- Telemetry added. In case of a feature if it's used or not.
- Errors have a helpful link attached, see
https://github.com/vercel/next.js/blob/canary/contributing.md


## For Maintainers

- Minimal description (aim for explaining to someone not on the team to
understand the PR)
- When linking to a Slack thread, you might want to share details of the
conclusion
- Link both the Linear (Fixes NEXT-xxx) and the GitHub issues
- Add review comments if necessary to explain to the reviewer the logic
behind a change

### What?

### Why?

### How?

Closes NEXT-
Fixes #

-->

let Rspack to pass the test cases it was previously able to pass.

1. update Rspack to 1.3.9
2. Moves `moduleSpansByCompilation` setting in `RspackProfilingPlugin`
from the `compilation` hook to `thisCompilation`.

`TraceEntryPointsPlugin` relies on `moduleSpansByCompilation` during its
`thisCompilation` hook. Since the `compilation` hook triggers before
`thisCompilation`, initializing the map earlier leads to:

  ```
Error: × TypeError: Cannot read properties of undefined (reading
'traceChild')
  ```
  
  relate: https://github.com/vercel/next.js/pull/78011
  
3. The test case
`test/integration/middleware-prefetch/tests/index.test.js` was failing
due to an unreliable asset name matching strategy.
  
Asset names follow the pattern:
`static/chunks/pages/[pagename]-[hash].js`.

Test was checking for `ssg-page-2-[hash].js` by looking for names
starting with `ssg-page-2`.

This could produce false positives when `ssg-page-[hash].js` happens to
have a hash starting with `2`.

4. test dev `test/e2e/app-dir/dynamic-data/dynamic-data.test.ts`

Test fails due to Rspack's lack of support for
compilation.codeGenerationResults JS API.

5.  test dev `test/e2e/app-dir/dynamic-href/dynamic-href.test.ts`

Same compatibility issue as above.

6.  test dev `test/development/acceptance-app/hydration-error.test.ts`

Same compatibility issue as above.

6. test dev `test/development/app-dir/ssr-in-rsc/ssr-in-rsc.test.ts`

Test fails due to differing error message formats between
implementations.