docs: fix button server action example (#70131)
When following the example for server actions for button onClick,
developers will see the error below.

```
Error: Only plain objects, and a few built-ins, can be passed to Server Actions. Classes or null prototypes are not supported.
```

That is because the server action function is taking in the button
onClick `event` in the action.

Co-authored-by: JJ Kasper <jj@jjsweb.site>